# Generated by Django 4.2.29 on 2026-03-11 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=200)),
                ("summary", models.TextField(blank=True)),
                ("skills", models.JSONField(default=list)),
                ("education_json", models.JSONField(default=list)),
                ("experience_json", models.JSONField(default=list)),
                ("projects_json", models.JSONField(default=list)),
                ("raw_text", models.TextField(blank=True)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="resumes/%Y/%m/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume",
                        to="students.studentprofile",
                    ),
                ),
            ],
        ),
    ]
